name: go_router_plus
description: Building blocks to manage app screens, access control and refresh notifiers.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^4.2.8

dev_dependencies:
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  mockito: ^5.3.0
  very_good_analysis: ^3.0.1
