name: 'Tests'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: 'Run tests'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        channel:
          - stable
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ matrix.channel }}
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
          cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:'
      - name: Get dependencies
        run: flutter pub get
      - name: Analyze
        run: flutter analyze
      - name: Tests
        run: flutter test --coverage
      - uses: codecov/codecov-action@v3
        with:
          directory: ./coverage